### ISSUE TITLE
Pattern [91m... failed

### ISSUE THREAD

**Issue by slavikfoxy** [EchterAlsFake/PHUB#46]
Pattern [91mid=\"(.*?)\".*?-vkey=\"(.*?)\".*?title=\"(.*?)\".*?src=\"(.*?)\".*?-mediabook=\"(.*?)\".*?marker-overlays.*?>(.*?)</div[0m failed
Traceback (most recent call last):
  File "C:\Users\oliyn\OneDrive\Documents\ghub\CheckMissVideo.py", line 191, in <module>
    imput()
  File "C:\Users\oliyn\OneDrive\Documents\ghub\CheckMissVideo.py", line 57, in imput
    for i, video in enumerate(client.account.watched):
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 109, in __iter__
    for item in page:
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 335, in _iter_page
    wrapped: QueryItem = self._parse_item(item)
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 305, in _parse_item
    data = self._eval_video(raw)
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 298, in _eval_video
    data = {k: v for k, v in zip(keys, consts.re.eval_video(raw))} | {'raw': raw}
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\consts.py", line 86, in wrapper
    raise errors.RegexError('Find regex failed.')
phub.errors.RegexError: Find regex failed.

how can I skip this error in the loop for i, video in enumerate(client.account.watched)

**Comment by slavikfoxy** [comment]
Can I access the list of my videos in the playlist?

**Comment by Egsagon** [comment]
Hi, you can skip errors by using `phub.utils.suppress`.
To access the lists of the videos you created in the playlist, you can simply filter videos that have you as an author:
```py
for video in client.account.watched.sample(filter = lambda v: v.author.name == 'your-name'):
    ...
```
Direct user objects comparisons is something that should be added in the future.

Concerning the regex error, can you share what videos/types raise these errors, so the project can be updated?

**Comment by slavikfoxy** [comment]
593
594
595
Pattern [91mid=\"(.*?)\".*?-vkey=\"(.*?)\".*?title=\"(.*?)\".*?src=\"(.*?)\".*?-mediabook=\"(.*?)\".*?marker-overlays.*?>(.*?)</div[0m failed
Traceback (most recent call last):
  File "C:\Users\oliyn\OneDrive\Documents\ghub\CheckMissVideo.py", line 195, in <module>
    input()
  File "C:\Users\oliyn\OneDrive\Documents\ghub\CheckMissVideo.py", line 59, in input
    for video in suppress(client.account.watched):
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\utils.py", line 229, in suppress
    raise err
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\utils.py", line 218, in suppress
    item = next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 109, in __iter__
    for item in page:
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 335, in _iter_page
    wrapped: QueryItem = self._parse_item(item)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 305, in _parse_item
    data = self._eval_video(raw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 298, in _eval_video
    data = {k: v for k, v in zip(keys, consts.re.eval_video(raw))} | {'raw': raw}
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\consts.py", line 86, in wrapper
    raise errors.RegexError('Find regex failed.')
phub.errors.RegexError: Find regex failed.
[Finished in 29.7s]

phub.utils.suppress did not help

**Comment by Egsagon** [comment]
You need to specify which error you need to supress. In your case, `phub.errors.RegexError`

**Comment by slavikfoxy** [comment]
I figured out how to use suppress, for video in suppress(client.account.watched, phub.errors.RegexError):but it exits the loop 
Pattern [91mid=\"(.*?)\".*?-vkey=\"(.*?)\".*?title=\"(.*?)\".*?src=\"(.*?)\".*?-mediabook=\"(.*?)\".*?marker-overlays.*?>(.*?)</div[0m failed
Suppressing the error Find regex failed..: RegexError('Find regex failed.')
and the function for video in (client.account.watched.sample(filter = lambda v: v.author.name == 'MyNaMe')):
         print(f'{video.title}'):
  does not print any result

**Comment by Egsagon** [comment]
Make sure you are using the right name (e.g. from client.account.name) and you have watched your videos.

**Comment by slavikfoxy** [comment]
<img width="1280" alt="image" src="https://github.com/EchterAlsFake/PHUB/assets/20266330/f6b0ae70-74cd-4376-868e-c70c7d7f15d5">
I can't get more than 47 videos, is it just me? it happened 3 days ago.

**Comment by Egsagon** [comment]
It's not just you. My history got striped out too. It's a problem on Pornhub side, and it sucks.

**Comment by slavikfoxy** [comment]
<img width="792" alt="image" src="https://github.com/EchterAlsFake/PHUB/assets/20266330/e1213696-521d-4d0b-bd8e-5682dd145c0d">
I think I broke my account )

**Comment by Egsagon** [comment]
at least there are no errors

**Comment by EchterAlsFake** [comment]
@slavikfoxy 

Hey, if you are still there...  If it would be possible for you, please update to the newest PHUB release and execute your script from february once again. If it still gives you the Pattern failed error, please run the same script again, but print out the URLs at the beginning, so that we can identify the exact video where it fails.  This would be great, thank you :)

**Comment by slavikfoxy** [comment]
924. https://www.pornhub.com/view_video.php?viewkey=65767498dbb2f
925. https://www.pornhub.com/view_video.php?viewkey=65a9177237741
Pattern <eval_video> failed
Traceback (most recent call last):
  File "C:\Users\oliyn\OneDrive\Documents\PYTHON PROJEKT\4.4\0CheckMissVideo.py", line 35, in <module>
    imput()
  File "C:\Users\oliyn\OneDrive\Documents\PYTHON PROJEKT\4.4\0CheckMissVideo.py", line 28, in imput
    raise e
  File "C:\Users\oliyn\OneDrive\Documents\PYTHON PROJEKT\4.4\0CheckMissVideo.py", line 20, in imput
    for i, video in enumerate(client.account.watched):
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 134, in __iter__
    for item in page:
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 331, in _iter_page
    wrapped: QueryItem = self._parse_item(item)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 304, in _parse_item
    data = self._eval_video(raw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\objects\query.py", line 297, in _eval_video
    data = {k: v for k, v in zip(keys, consts.re.eval_video(raw))} | {'raw': raw}
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\consts.py", line 113, in wrapper
    _throw_re_error(pattern)
  File "C:\Users\oliyn\AppData\Local\Programs\Python\Python312\Lib\site-packages\phub\consts.py", line 78, in _throw_re_error
    raise errors.RegexError(f'Regex <{regex_name}> failed.')
phub.errors.RegexError: Regex <eval_video> failed.
[Finished in 20.1s]

**Comment by slavikfoxy** [comment]
What code should I write to get the url of 926 videos?

**Comment by slavikfoxy** [comment]
phub.Video(key=65ac5d1a2b3d4),  on version 4.2.0 the pattern works
<img width="1278" alt="image" src="https://github.com/EchterAlsFake/PHUB/assets/20266330/e4b77544-710f-4bb2-9d30-5baa3c72c20b">

**Comment by Egsagon** [comment]
Hey, this should be fixed now. Please update from the latest commit and tell us if it works.
