### ISSUE TITLE
Pattern <get_flash> failed

### ISSUE THREAD

**Issue by rlleshi** [EchterAlsFake/PHUB#70]
I've installed the latest dev version. If we run the following snippet: 

```
import phub

client = phub.Client()
query = client.search(query="sloppy",
                           category='amateur',
                           sort='recent',
                           production='homemade')

for video in query.sample(100):
    print(video.title)
    print(video.url)
    print(video.author)
    print('\n\n')
```

It'll eventually fail when trying to grab the author with:

```
Pattern <get_flash> failed
Traceback (most recent call last):
  File "phub_reproduce.py", line 13, in <module>
    print(video.author)
  File ".pyenv/versions/3.9.0/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File ".pyenv/versions/source_faces/lib/python3.9/site-packages/phub/objects/video.py", line 577, in author
    return User.from_video(self)
  File ".pyenv/versions/source_faces/lib/python3.9/site-packages/phub/objects/user.py", line 103, in from_video
    video.fetch('page@')
  File ".pyenv/versions/source_faces/lib/python3.9/site-packages/phub/objects/video.py", line 144, in fetch
    data = parser.resolve(self)
  File ".pyenv/versions/source_faces/lib/python3.9/site-packages/phub/modules/parser.py", line 39, in resolve
    flash, ctx = consts.re.get_flash(video.page)
  File ".pyenv/versions/source_faces/lib/python3.9/site-packages/phub/consts.py", line 132, in wrapper
    _throw_re_error(pattern)
  File ".pyenv/versions/source_faces/lib/python3.9/site-packages/phub/consts.py", line 97, in _throw_re_error
    raise errors.RegexError(f'Regex <{regex_name}> failed.')
phub.errors.RegexError: Regex <get_flash> failed.
```

Not sure why it cannot parse the author name. But regardless I think it would be better that it does not fail the loop but rather just returns None for the author name? Or perhaps some error handling improvement so that we know the reason is in order.

**Comment by EchterAlsFake** [comment]
I just ran your eample and opened the URL where it failed and it was a PornHub premium video, which is the reason why it can not fetch the author. I will add an exception class for that case.

I and Egsagon have not implemented PornHub Premium in any way, since we don't have an account to test with and it would also be a bit out of scope for what this project is intended for. 

Thanks for reporting, have an awesome day :)

**Comment by rlleshi** [comment]
Hey, thanks for the quick response.

I see, makes sense. But I actually used `free_premium=False` in sample & the error was still thrown. What does this bool actually stand for?

**Comment by Egsagon** [comment]
It's for when the video is supposed to be premium, but is (temporarily) free.
